### ISSUE TITLE
The Server crashed, 

### ISSUE THREAD

**Issue by zackxue** [SpecForge/html5_rtsp_player#13]
we use Ubuntu 16.04 x64, and use Axis Camera rtsp source.

Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4314700 (LWP 6472)]
[New Thread 0x7ffff3b13700 (LWP 6473)]
[New Thread 0x7ffff3312700 (LWP 6474)]
[New Thread 0x7ffff2b11700 (LWP 6475)]
[New Thread 0x7ffff2310700 (LWP 6476)]
[New Thread 0x7ffff1b0f700 (LWP 6477)]
[New Thread 0x7ffff130e700 (LWP 6478)]
[New Thread 0x7ffff0b0d700 (LWP 6479)]

Thread 3 "websock_rtsp_pr" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff3b13700 (LWP 6473)]
__lll_unlock_elision (lock=0x7fffffffe370, private=0)
    at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
29      ../sysdeps/unix/sysv/linux/x86/elision-unlock.c: No such file or directory.

**Comment by zackxue** [comment]
#0  __lll_unlock_elision (lock=0x7fffffffdd00, private=0) at ../sysdeps/unix/sysv/linux/x86/elision-unlock.c:29
#1  0x00000000004835ba in WebSocketServer::on_rtsp_connect(std::shared_ptr<websocketpp::connection<websocketpp::config::asio> >) ()
#2  0x0000000000483832 in WebSocketServer::validate(std::weak_ptr<void>) ()
#3  0x000000000048dbb9 in std::_Function_handler<bool (std::weak_ptr<void>), std::_Bind<std::_Mem_fn<bool (WebSocketServer::*)(std::weak_ptr<void>)> (WebSocketServer*, std::_Placeholder<1>)> >::_M_invoke(std::_Any_data const&, std::weak_ptr<void>&&) ()
#4  0x00000000004a9d62 in websocketpp::connection<websocketpp::config::asio>::process_handshake_request() ()
#5  0x00000000004aa33d in websocketpp::connection<websocketpp::config::asio>::handle_read_handshake(std::error_code const&, unsigned long) ()
#6  0x0000000000495c12 in websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::handle_async_read(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long) ()
#7  0x0000000000499007 in void boost::asio::detail::strand_service::dispatch<boost::asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::system::error_code, unsigned long> >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::binder2<websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::system::error_code, unsigned long>&) ()
#8  0x0000000000499389 in void boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::asio::detail::is_continuation_if_running>::operator()<boost::system::error_code, unsigned long>(boost::system::error_code const&, unsigned long const&) ()
#9  0x0000000000499716 in boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::asio::detail::is_continuation_if_running> >::operator()(boost::system::error_code const&, unsigned long, int) ()
#10 0x00000000004a84d1 in boost::asio::detail::completion_handler<boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::asio::detail::is_continuation_if_running> >, boost::system::error_code, unsigned long>, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> > > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#11 0x00000000004a87ec in void boost::asio::detail::strand_service::dispatch<boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::asio::detail::is_continuation_if_running> >, boost::system::error_code, unsigned long>, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> > > >(boost::asio::detail::strand_service::strand_impl*&, boost::asio::detail::rewrapped_handler<boost::asio::detail::binder2<boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::asio::detail::is_continuation_if_running> >, boost::system::error_code, unsigned long>, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> > >&) ()
#12 0x00000000004a8c63 in boost::asio::detail::reactive_socket_recv_op<boost::asio::mutable_buffers_1, boost::asio::detail::read_op<boost::asio::basic_stream_socket<boost::asio::ip::tcp, boost::asio::stream_socket_service<boost::asio::ip::tcp> >, boost::asio::mutable_buffers_1, boost::asio::detail::transfer_at_least_t, boost::asio::detail::wrapped_handler<boost::asio::io_service::strand, websocketpp::transport::asio::custom_alloc_handler<std::_Bind<std::_Mem_fn<void (websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config>::*)(std::function<void (std::error_code const&, unsigned long)>, boost::system::error_code const&, unsigned long)> (std::shared_ptr<websocketpp::transport::asio::connection<websocketpp::config::asio::transport_config> >, std::function<void (std::error_code const&, unsigned long)>, std::_Placeholder<1>, std::_Placeholder<2>)> >, boost::asio::detail::is_continuation_if_running> > >::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#13 0x000000000048a13d in boost::asio::detail::epoll_reactor::descriptor_state::do_complete(boost::asio::detail::task_io_service*, boost::asio::detail::task_io_service_operation*, boost::system::error_code const&, unsigned long) ()
#14 0x000000000048b94d in websocketpp::transport::asio::endpoint<websocketpp::config::asio::transport_config>::run() ()
#15 0x00007ffff7166c80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#16 0x00007ffff7bc16fa in start_thread (arg=0x7ffff3b13700) at pthread_create.c:333
#17 0x00007ffff6bd5b5d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) quit
A debugging session is active.

**Comment by zackxue** [comment]
Change to another, it ok.
